fixing workflow

diff --git a/.github/workflows/videos-two-jobs.yml b/.github/workflows/videos-two-jobs.yml
--- a/.github/workflows/videos-two-jobs.yml
+++ b/.github/workflows/videos-two-jobs.yml
@@ -16,8 +16,6 @@ on:
 jobs:
   get-access-token:
     runs-on: ubuntu-latest
-    outputs:
-      access_token: ${{ steps.get-token.outputs.access_token }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
@@ -31,29 +29,34 @@ jobs:
           PORT_CLIENT_ID: ${{ secrets.PORT_CLIENT_ID }}
           PORT_CLIENT_SECRET: ${{ secrets.PORT_CLIENT_SECRET }}
         run: |
-          # Request access token
           access_token=$(curl --location --request POST 'https://api.getport.io/v1/auth/access_token' \
           --header 'Content-Type: application/json' \
           --data-raw "{
               \"clientId\": \"$PORT_CLIENT_ID\",
               \"clientSecret\": \"$PORT_CLIENT_SECRET\"
           }" | jq -r '.accessToken')
-          echo "::set-output name=access_token::$access_token"
+
+          if [ -z "$access_token" ]; then
+            echo "Failed to retrieve access token. Exiting."
+            exit 1
+          fi
+
+          echo "ACCESS_TOKEN=$access_token" >> $GITHUB_ENV
+
+      - name: Debug Access Token
+        run: echo "Access token: $ACCESS_TOKEN"
 
   upsert-playlist-data:
     runs-on: ubuntu-latest
     needs: get-access-token
-    env:
-      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
     steps:
       - name: Install jq
         run: sudo apt-get install -y jq
 
       - name: Fetch and Upsert YouTube Playlist Data to Port
         env:
-          ACCESS_TOKEN: ${{ needs.get-access-token.outputs.access_token }}
+          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
         run: |
-          # Validate ACCESS_TOKEN
           if [ -z "$ACCESS_TOKEN" ]; then
             echo "ACCESS_TOKEN is not set. Exiting."
             exit 1
@@ -65,12 +68,9 @@ jobs:
 
           # Initialize nextPageToken
           nextPageToken=""
-
           while true; do
-              # Fetch videos in the playlist (one page at a time)
               response=$(curl -s "https://www.googleapis.com/youtube/v3/playlistItems?part=snippet,contentDetails&playlistId=$PLAYLIST_ID&maxResults=50&pageToken=$nextPageToken&key=$YOUTUBE_API_KEY")
 
-              # Parse and iterate over each video
               echo "$response" | jq -c '.items[]?' | while read -r item; do
                   video_id=$(echo "$item" | jq -r '.contentDetails.videoId')
                   title=$(echo "$item" | jq -r '.snippet.title')
@@ -137,10 +137,7 @@ jobs:
     needs: upsert-playlist-data
     steps:
       - name: Report Status to Port
-        env:
-          ACCESS_TOKEN: ${{ needs.get-access-token.outputs.access_token }}
         run: |
-          # Validate ACCESS_TOKEN
           if [ -z "$ACCESS_TOKEN" ]; then
             echo "ACCESS_TOKEN is not set. Exiting."
             exit 1
